### ISSUE TITLE
answer: yes

### ISSUE THREAD

**Issue by msimerson** [verficon/slackmail#2]
> // TODO: should this be outside the hook? (as it watches for changes I believe)
>   var cfg = plugin.config.get('slack.ini');

Yes, put this in an initialization function. 

``` js
exports.register = function() {
    var plugin = this;
    plugin.load_slack_ini();
}

exports.load_slack_ini = function () {
    var plugin = this;
    plugin.cfg = plugin.config.get('slack.ini', function () {
        plugin.load_slack_ini();
    });
}
```

Now your config will get loaded up once at register time, with a callback in case it changes. After the config file changes, the callback will trigger and plugin.cfg will get updated.

**Comment by m-rd-r** [comment]
I thought the API said it would automatically apply changes to the object (as per default value).

I'll dive into Haraka's source code when I get back on the computer. See how it works internally.

**Comment by msimerson** [comment]
> it would automatically apply changes to the object

Yes and no. Your 'var cfg' object will get updated automatically that way, but it calls the config file loader upon _every_ hook_rcpt (millions or billions of times), whether the config needs to be updated or not. It's more efficient to cache that config and only ever call plugin.config.get when the file changes, which is what the code I showed does. 

Granted, this matters little with your teeny little file, but it matters a whole lot if your config file(s) get very large.

**Comment by m-rd-r** [comment]
Good call on just the object initiation alone. I will apply your suggested code.
