### ISSUE TITLE
two code paths in hook_rcpt

### ISSUE THREAD

**Issue by msimerson** [verficon/slackmail#3]
```
if ((now() - lastUpdate) > ttl) {
    return getUsers(cfg.tokens[params[0].host], function(err, fresh) { // TODO: handle this error
        users[params[0].host] = fresh;
        cache[params[0].host] = now();
            stage2.call(plugin, next, conn, params);
    });
}
stage2.call(plugin, next, conn, params);
```

I would make hook_rcpt more deterministic. Rather than putting the refresh in there, I'd put a call to the update function in `register()`.

Instead of checking the date on every call, you could have the call in `register()` be recursive, so that it automatically updates every NNN seconds. Then your rcpt_to hook is dead simple: is the domain and user in the list, or not?

**Comment by m-rd-r** [comment]
The idea is not to spam Slack with API requests if you want a low ttl.

I considered setInterval first and settled with this.

The code could be made a lot cleaner with a Promise, but I don't want to have another dependency for users (bluebird)

**Comment by msimerson** [comment]
> not to spam Slack with API requests if you want a low ttl

Right, but you don't need promises for that. The point is to make hook_rcpt simpler, ie just doing rcpt_to stuff in the rcpt_hook. Sure, you might also have a call to update_slack_users, but that typically does nothing (ttl hasn't expired). When it does do something, it doesn't affect rcpt_to (besides updating the DB it users).

**Comment by m-rd-r** [comment]
Hmm, the current design was chosen because it also does the first user retrieval in the same process. But I will be refining this code with your suggestions. Thank you for your input Matt.
